FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

COPY package.json pnpm-workspace.yaml tsconfig.base.json eslint.config.js ./
COPY packages ./packages
COPY apps/api ./apps/api
RUN pnpm install --frozen-lockfile=false
RUN pnpm --filter @sparta/api prisma:generate
RUN pnpm --filter "@sparta/api..." build

EXPOSE 3333
CMD ["pnpm", "--filter", "@sparta/api", "start"]
